version: '3.9'

volumes:
    db_data:
        name: db_data
    cache_data:
        name: cache_data

services:
  redis:
    container_name: "${PROJECT_NAME}-redis"
    image: redis:6.2.5-alpine
    command: redis-server --appendonly yes
    volumes:
      - cache_data:/var/lib/redis/data
    ports:
      - '127.0.0.1:6380:6380'

  postgres:
    container_name: "${PROJECT_NAME}-postgres"
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ~/.psqlrc:/root/.psqlrc:ro  # client psql config
      - ~/.psql_history:/root/.psql_history  # client psql history
    ports:
      - '127.0.0.1:5433:5433'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_DB: backend

  web:
    container_name: "${PROJECT_NAME}-web"
    restart: always
    entrypoint: scripts/entrypoint.sh
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
      args:
        INSTALL_ARGS: "--no-root"
    ports:
      - '127.0.0.1:8001:8000'
    volumes:
      - '.:/app'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: postgres
      # Used by entrypoint.sh
      DATABASE_URL: "postgresql+asyncpg://postgres:pg_pass@${PROJECT_NAME}-postgres/backend"
      REDIS_URL: "redis://${PROJECT_NAME}-redis"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@star.lite
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
